spring:
  datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: h2
    password:
    driver-class-name: org.hd.Driver
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true
          format_sql: true
    h2:
      console:
        enable: true
        path: /console




